"use client";

import React, { useState, useEffect } from "react";
import { API_BASE, safeFetch } from "../utils/api";
import { Briefcase, XCircle, ArrowUpRight, ArrowDownRight } from "lucide-react";

export default function PositionsTable() {
  const [positions, setPositions] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  const fetchPositions = () => {
    safeFetch(`${API_BASE}/api/execution/positions`)
      .then((res) => res.json())
      .then((data) => {
        if (data.positions) setPositions(data.positions);
      })
      .catch((err) => console.warn("Positions API offline:", err));
  };

  useEffect(() => {
    fetchPositions();
    const timer = setInterval(fetchPositions, 3000);
    return () => clearInterval(timer);
  }, []);

  const handleClosePosition = (positionId: string, currentPrice: number) => {
    setLoading(true);
    safeFetch(`${API_BASE}/api/execution/positions/${encodeURIComponent(positionId)}/close`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ exit_price: currentPrice })
    })
      .then((res) => res.json())
      .then(() => fetchPositions())
      .catch((err) => console.error("Error closing position:", err))
      .finally(() => setLoading(false));
  };

  const handleCloseAll = () => {
    setLoading(true);
    safeFetch(`${API_BASE}/api/execution/close-all`, {
      method: "POST"
    })
      .then((res) => res.json())
      .then(() => fetchPositions())
      .catch((err) => console.error("Error closing all positions:", err))
      .finally(() => setLoading(false));
  };

  return (
    <div className="bg-white border border-slate-200/80 rounded-2xl p-5 shadow-xs font-sans space-y-4">
      <div className="flex items-center justify-between border-b border-slate-100 pb-3">
        <div className="flex items-center gap-2.5">
          <Briefcase className="w-4 h-4 text-blue-600" />
          <h3 className="text-sm font-extrabold text-slate-900">Active Signals & Positions</h3>
          <span className="text-xs bg-blue-50 text-blue-700 border border-blue-200 px-2.5 py-0.5 rounded-full font-mono font-bold">
            {positions.length} Open
          </span>
        </div>
        {positions.length > 0 && (
          <button
            onClick={handleCloseAll}
            disabled={loading}
            className="text-xs bg-rose-50 text-rose-600 hover:bg-rose-100 border border-rose-200 px-3.5 py-1.5 rounded-xl font-bold transition flex items-center gap-1.5 shadow-xs"
          >
            <XCircle className="w-3.5 h-3.5" />
            <span>Close All Positions</span>
          </button>
        )}
      </div>

      {positions.length === 0 ? (
        <div className="text-center py-6 text-slate-400 text-xs font-medium">
          No open positions. Active trades and live signals generated by the execution engine will appear here.
        </div>
      ) : (
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-50 text-slate-500 uppercase text-[10px] tracking-wider border-b border-slate-200 font-extrabold">
              <tr>
                <th className="p-3">Symbol</th>
                <th className="p-3">Direction</th>
                <th className="p-3">Lots</th>
                <th className="p-3">Entry</th>
                <th className="p-3">Stop Loss</th>
                <th className="p-3">Take Profit 2</th>
                <th className="p-3">PnL ($)</th>
                <th className="p-3 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {positions.map((pos) => {
                const isBuy = pos.direction === "BUY" || pos.direction === "long";
                return (
                  <tr key={pos.position_id} className="hover:bg-slate-50 transition">
                    <td className="p-3 font-extrabold text-blue-600">{pos.symbol}</td>
                    <td className="p-3">
                      <span
                        className={`px-2.5 py-0.5 rounded font-extrabold text-[10px] inline-flex items-center gap-1 ${
                          isBuy ? "bg-emerald-50 text-emerald-700 border border-emerald-200" : "bg-rose-50 text-rose-700 border border-rose-200"
                        }`}
                      >
                        {isBuy ? <ArrowUpRight className="w-3 h-3" /> : <ArrowDownRight className="w-3 h-3" />}
                        {pos.direction.toUpperCase()}
                      </span>
                    </td>
                    <td className="p-3 font-mono font-bold text-slate-700">{pos.size_lots}</td>
                    <td className="p-3 font-mono font-bold text-slate-800">${pos.entry_price?.toFixed(2)}</td>
                    <td className="p-3 font-mono font-bold text-rose-600">${pos.stop_loss?.toFixed(2)}</td>
                    <td className="p-3 font-mono font-bold text-emerald-600">${pos.take_profit_2?.toFixed(2)}</td>
                    <td
                      className={`p-3 font-black font-mono text-xs ${
                        (pos.unrealized_pnl || 0) >= 0 ? "text-emerald-600" : "text-rose-600"
                      }`}
                    >
                      ${(pos.unrealized_pnl || 0) >= 0 ? "+" : ""}
                      {pos.unrealized_pnl?.toFixed(2) || "0.00"}
                    </td>
                    <td className="p-3 text-right">
                      <button
                        onClick={() => handleClosePosition(pos.position_id, pos.current_price || pos.entry_price)}
                        disabled={loading}
                        className="px-3 py-1 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-lg font-bold text-xs transition border border-slate-200 shadow-xs"
                      >
                        Close
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
